name: Core service test
permissions:
  contents: read

on: [push, workflow_dispatch]


jobs:
  test_package:
    name: Test ${{ matrix.os }} Python ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04"]
        python_version: ["3.12"]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@caf0cab7a618c569241d31dcd442f54681755d39 # v3.2.4
        with:
          version: "latest"
          architecture: x64
      - name: Install dependencies
        run: |
          cd ./mucgpt-core-service
          uv sync --all-extras
      - name: Lint with ruff
        run: |
          cd ./mucgpt-core-service
          uv run ruff check .
      - name: Run Python tests
        run: |
          cd ./mucgpt-core-service
          uv run pytest
